version: '3'
services:
  backend:
    image: avngrstark62/backend:latest  # Use the Docker Hub image
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    image: avngrstark62/frontend:latest  # Use the Docker Hub image
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    restart: always

