version: '3.8'

services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"                  # Expose Nginx on port 80
    volumes:
      - ./frontend/dist:/usr/share/nginx/html   # Mount built frontend files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # Use your Nginx config
    depends_on:
      - backend                  # Ensure backend starts first
    restart: always

  backend:
    image: avngrstark62/clown-backend:latest
    ports:
      - "8000:8000"              # Map backend port
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: always

