version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Vite default port
    volumes:
      - ./frontend:/app  # Mount frontend source code
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Mount backend source code
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    depends_on:
      - ai-service  # Ensure AI service starts before the backend
    restart: always

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile.dev  # Use a separate dev Dockerfile for AI service
    ports:
      - "8001:8001"
    volumes:
      - ./ai-service:/app  # Mount AI service source code
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs are immediately visible
    env_file:
      - ./ai-service/.env
    restart: always